
name: Publish to PyPI (Trusted Publisher)

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # required for Trusted Publisher OIDC to PyPI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools wheel twine

      - name: Build sdist and wheel
        run: |
          python -m build
          python -m pip freeze

      - name: Twine check
        run: |
          python -m twine check dist/*

      # Publish to PyPI using an API token
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          attestations: true
